### ISSUE TITLE
Feature suggestion: use api token

### ISSUE THREAD

**Issue by Nipsuli** [arddluma/cloudflare-pages-slack-notification#10]
In addition of email + api key it would be nice if one could use cloudflare api token to limit the scope one gives access to.

**Comment by arddluma** [comment]
hey @Nipsuli !
Thanks for suggestion, I have been thinking of this a lot but didn't get the chance to start on this...

**Comment by arddluma** [comment]
Hey there @Nipsuli , finally got some time to finish this.
Please feel free to check out new version `v3` , remember to add ( apiToken: ${{ secrets.CF_API_TOKEN }} ) and remove 
       ` apiKey: ${{ secrets.CF_API_KEY  }} `and `accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL }}`
```   
 - name: Send Slack deployment notifications
      uses: arddluma/cloudflare-pages-slack-notification@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACC_ID  }}
        project: ${{ secrets.CF_PROJECT  }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        slackWebHook: ${{ secrets.SLACK_WEBHOOK  }}``

Please let me know once you try! Thank you

**Comment by Nipsuli** [comment]
This is so awesome! I'll update our CI later today. Thank you so so much 🙇

**Comment by arddluma** [comment]
Closing as completed. Feature is ready to use on v3
