### ISSUE TITLE
Make slackWebHook optional

### ISSUE THREAD

**Issue by salexpro** [arddluma/cloudflare-pages-slack-notification#3]
Is it possible to make slack messages optional? For example, we have already messages from github in our slack, but we need development env/status for PRs, github also sends messages about it to slack so a separate message is not required. But the main issue is when I delete Slack token from the action it throws an error

**Comment by arddluma** [comment]
hey @salexpro, could you please clarify this. I don't understand the use case here. 
It is not a problem to make it optional but I don't understand the reason for this.
Thanks in advance!

**Comment by salexpro** [comment]
Sorry if I confused you a little. So the thing is that we already have github connected to our slack and it's sending deploy messages which are this action adds to PRs
<img width="587" alt="image" src="https://user-images.githubusercontent.com/4237964/169624594-a27b35e4-e6be-44cc-bf05-5dff20701236.png">
and basically, there's no need to "duplicate" that info with another slack app/webhook
<img width="551" alt="image" src="https://user-images.githubusercontent.com/4237964/169624697-84d864d2-534a-4d3f-9bdc-476bfbdf2390.png">
I think it would be nice to make `slackWebHook: ${{ secrets.SLACK_WEBHOOK  }}` an optional thing since we're already getting status messages from GitHub and it's also one less secret to add to every new repo

**Comment by arddluma** [comment]
Thanks for your response!
Ah, I see! But the whole point of this action is to send Slack notifications with additional info like deployment id ,url and also logs to make it easier and not via GitHub deployments notifications.
I will make it optional in the next release 🙏

**Comment by salexpro** [comment]
Thanks! Much appreciated!

**Comment by arddluma** [comment]
Hello @salexpro , 
I've just made SlackWebHook optional, feel free to try `arddluma/cloudflare-pages-slack-notification@v2.2`and let me know :)
However, you also have the option to unsubscribe to deployment events in GitHub Slack app `/github unsubscribe owner/repo deployments` 
Thanks!

**Comment by arddluma** [comment]
@salexpro could you please close this issue once you are satisfied with it :) Thanks!

**Comment by salexpro** [comment]
Sure, thanks!
