### ISSUE TITLE
Some warnings from the package 

### ISSUE THREAD

**Issue by adheegm** [arddluma/cloudflare-pages-slack-notification#5]
Hello @arddluma 

The package return these kind of warnings
1. Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: arddluma/cloudflare-pages-slack-notification
![image](https://user-images.githubusercontent.com/1817786/196011948-3c6db399-0a18-4bb1-95fe-362338085be7.png)

2. The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
![image](https://user-images.githubusercontent.com/1817786/196011960-2cae7b17-1a0f-4cbc-bde2-2ed152e4dff8.png)

Seems like need to update `@action/core` to the latest version https://github.com/actions/setup-node/pull/590 https://github.com/actions/setup-node/issues/589

**Comment by amitkoth** [comment]
@arddluma echoing this above :) Really appreciate your help

**Comment by arddluma** [comment]
hey @adheegm ,
Thanks for reporting this, I will fix this soon and let you know.

**Comment by arddluma** [comment]
hey @adheegm @amitkoth,
I have just pushed a fix for this, please update the version to  2.5 `arddluma/cloudflare-pages-slack-notification@v2.5`
In case Node.js 12 warning is not removed you may have to update actions/checkout to v3 `actions/checkout@v3` 
Please let me know if fix works. 
Thanks guys!

**Comment by adheegm** [comment]
@arddluma Thanks so much -  We don't see any warning anymore. Closing this ticket cc @amitkoth

**Comment by amitkoth** [comment]
Awesome, thanks @arddluma
