### ISSUE TITLE
Using action with workflow_dispatch gives TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by Davste93** [arddluma/cloudflare-pages-slack-notification#7]
Hi,

First of all thank you for this action! Much better than waiting on Cloudflare to support hooks for sure 😄 

For context: I'm running Cloudflare pages builds not just on push but also via API deployments.

I tried running this action via workflow_dispatch (https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event) on master (`{"ref": "refs/heads/master"}`) but I get the following after the deploy step:

```
Waiting for Pages to finish building...
(node:1616) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
# Now at stage: build
# Now at stage: deploy
/home/runner/work/_actions/arddluma/cloudflare-pages-slack-notification/v2.5/dist/action.js:[12](https://github.com/allfront/allfront-marketing-new/actions/runs/3372632941/jobs/5596288290#step:3:13)823
Commit: ${import_utils.context.payload.head_commit.url}
                                                   ^

TypeError: Cannot read properties of undefined (reading 'url')
    at run (/home/runner/work/_actions/arddluma/cloudflare-pages-slack-notification/v2.5/dist/action.js:12823:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Davste93** [comment]
Fixed & tested here: https://github.com/arddluma/cloudflare-pages-slack-notification/pull/8

I also noticed a mismatching type "failure" vs "failed", idk what was the correct one but I assume it's the one coming from the type definition so I changed it also

**Comment by arddluma** [comment]
Hello @Davste93 , 
Thank you so much for this report, 
Unfortunately, I didn't take into consideration this type of deployment and I've added commit URL included in github context :/
Do you mind sharing your whole pipeline config? 
I will try to fix this soon ! 
Thanks again.

**Comment by mwillema** [comment]
I have a similar issue, see the screenshot below.

![Screenshot 2023-07-18 at 11 28 53](https://github.com/arddluma/cloudflare-pages-slack-notification/assets/8983537/7ea55b1d-37a0-4683-b39a-89bbb39d60fc)

**Comment by arddluma** [comment]
Could you please try out using `arddluma/cloudflare-pages-slack-notification@v4` ? Thanks

**Comment by arddluma** [comment]
> Could you please try out using `arddluma/cloudflare-pages-slack-notification@v4` ? Thanks

@Davste93 @mwillema sers, could you please check ?

**Comment by mwillema** [comment]
Indeed it works, thanks a lot!
